SELECT cc.ID_CLIENT, BB.NUM_DOC
FROM TABLE_CLIENTS cc
INNER JOIN TABLE_BB bb
ON CC.ID_CLIENT = BB.FKCLIENTE;

SELECT cc.ID_CLIENT, BB.NUM_DOC
FROM TABLE_CLIENTS cc
LEFT JOIN TABLE_BB bb
ON CC.ID_CLIENT = BB.FKCLIENTE;

SELECT cc.ID_CLIENT, BB.NUM_DOC
FROM TABLE_CLIENTS cc
RIGHT JOIN TABLE_BB bb
ON CC.ID_CLIENT = BB.FKCLIENTE;



SELECT cc.ID_CLIENT, BB.NUM_DOC
FROM TABLE_CLIENTS cc
FULL JOIN TABLE_BB bb
ON CC.ID_CLIENT = BB.FKCLIENTE;